### PR TITLE
translate: add support for `2.2.0` to `3.1.0`

### PR DESCRIPTION
**Pull request by tormath1**
Hi,

In this PR, we add the support to `ign-converter` for config translating from `2.2.0` to `3.1.0` in complement of other existing translations.

### CODE REVIEW

**Comment by tormath1** [comment]
@bgilbert thanks for your answer.
>  Ignition's existing translation code to convert the 2.2 config to 2.4

are you referring to [`v2_4.Translate`](https://github.com/coreos/ignition/blob/spec2x/config/v2_4/translate.go#L37) ?

**Comment by bgilbert** [comment]
Yup.

**Comment by bgilbert** [comment]
(For context, I'm trying to limit the number of distinct pairs of translations we carry.  If there's a reason to carry an explicit translation, we can, but I think the approach in https://github.com/coreos/ign-converter/pull/29#issuecomment-919356359 should work fine.)

**Comment by tormath1** [comment]
Hi,

> I'm trying to limit the number of distinct pairs of translations we carry.

I totally understand - and I was not aware of the native `Translate` method for each config version, thanks !

I tried the mentioned approach:
```
dataIn --Parse--> cfg22 --translate--> cfg23 --translate --> cfg24 --> v24to31
```
but I'm keep hitting the following error (why this PR is opened):
```
Failed to translate config from 2 to 3: Invalid input config:
deprecated: size is deprecated; use sizeMB instead
deprecated: start is deprecated; use startMB instead
deprecated: size is deprecated; use sizeMB instead
deprecated: start is deprecated; use startMB instead
```

Inspecting the codebase, I see that when we translate using [`v2_4.Translate`](https://github.com/coreos/ignition/blob/4db553d21ad7ce6971a348ef9b6dbc380103ef0b/config/v2_4/translate.go#L207-L210) - we keep the deprecated reference to `x.Size` (and `x.Start`) so this one is never actually translated from `size` to `sizeMiB` (and `start` to `startMiB`) that's why we hit this [validation](https://github.com/coreos/ignition/blob/4db553d21ad7ce6971a348ef9b6dbc380103ef0b/config/v2_4/types/partition.go#L48-L53) error.

Patching the vendor with something like:
```diff
diff --git a/vendor/github.com/coreos/ignition/config/v2_4/translate.go b/vendor/github.com/coreos/ignition/config/v2_4/translate.go
index b95c4ad..401465c 100644
--- a/vendor/github.com/coreos/ignition/config/v2_4/translate.go
+++ b/vendor/github.com/coreos/ignition/config/v2_4/translate.go
@@ -200,14 +200,22 @@ func Translate(old from.Config) types.Config {
        translatePartitionSlice := func(old []from.Partition) []types.Partition {
                var res []types.Partition
                for _, x := range old {
+                       size := x.SizeMiB
+                       if x.Size != nil {
+                               size = x.Size
+                       }
+
+                       start := x.StartMiB
+                       if x.Start != nil {
+                               start = x.Start
+                       }
+
                        res = append(res, types.Partition{
                                GUID:               x.GUID,
                                Label:              x.Label,
                                Number:             x.Number,
-                               Size:               x.Size,
-                               SizeMiB:            x.SizeMiB,
-                               Start:              x.Start,
-                               StartMiB:           x.StartMiB,
+                               SizeMiB:            size,
+                               StartMiB:           start,
                                TypeGUID:           x.TypeGUID,
                                ShouldExist:        x.ShouldExist,
                                WipePartitionEntry: x.WipePartitionEntry
```

seems to do the trick. To be more accurate, the patch should be applied on `config.v2_3` actually since it seems this option is deprecated starting from this version.

**Comment by bgilbert** [comment]
Ah, I see.  `start`/`size` can't be automatically translated to `startMiB`/`sizeMiB` without access to the target disk, since `start`/`size` are denominated in sectors and we don't know the sector size.  That's the reason `startMiB`/`sizeMiB` were introduced in the first place.

**Comment by tormath1** [comment]
@bgilbert oh ok, I thought it was just a simple rewording in order to precise the unit in the key name. So there is no way to translate configuration with `size` to configuration with `sizeMiB` if I understand correctly ?

**Comment by bgilbert** [comment]
That's right.  The user should manually switch their configs to the MiB fields in that case.

**Comment by tormath1** [comment]
Ok, thanks for this information. I'm closing this PR then !

**Pull request closed without merging**
