### PR TITLE
README: add more details and TODO section

### PR DESCRIPTION
**Pull request by yuqi-zhang**

### CODE REVIEW

**Comment by yuqi-zhang** [comment]
Do you know who has write access to this repo? I don't seem to have any.

**Comment by arithx** [comment]
I do not, maybe @bgilbert or @nstielau know.

**Comment by bgilbert** [comment]
I don't have any either.  Will follow up.

**Comment by bgilbert** [comment]
I gave team-os-internal-tools write access.  That might not be the best team but it's a start.

**Pull request merged**
